import {
  SiPhp,
  SiJavascript,
  SiPython,
  SiReact,
  SiNextdotjs,
  SiJquery,
  SiVercel,
  SiNodedotjs,
  SiExpress,
  SiSymfony,
  SiBootstrap,
  SiTailwindcss,
  SiPostgresql,
  SiMysql,
  SiMariadb,
  SiMongodb,
  SiDocker,
  SiGithub,
  SiWordpress,
  SiGrafana,
  SiMoodle,
  SiTypescript,
} from "react-icons/si";
import { FaJava } from "react-icons/fa";
import type { IconType } from "react-icons";

export const techIcons: Record<string, IconType> = {
  PHP: SiPhp,
  JavaScript: SiJavascript,
  Python: SiPython,
  Java: FaJava,
  React: SiReact,
  "Next.js": SiNextdotjs,
  jQuery: SiJquery,
  Vercel: SiVercel,
  "Node.js": SiNodedotjs,
  Express: SiExpress,
  "Express.js": SiExpress,
  Symfony: SiSymfony,
  Bootstrap: SiBootstrap,
  "Tailwind CSS": SiTailwindcss,
  PostgreSQL: SiPostgresql,
  MySQL: SiMysql,
  MariaDB: SiMariadb,
  MongoDB: SiMongodb,
  Docker: SiDocker,
  GitHub: SiGithub,
  Wordpress: SiWordpress,
  Grafana: SiGrafana,
  Moodle: SiMoodle,
  TypeScript: SiTypescript,
};
